In [1]:
import sys
sys.path.append('../../')
from PreprocessingMethods import StandardPreprocessor
import pandas as pd

In [2]:
df = pd.read_csv("hf://datasets/CitrusBoy/EnergyPriceForecasting/final_dataset_full_clean_with_gas_no_processing.csv")
df["time"] = pd.to_datetime(df["time"])

# Standard Preprocessor

This is how the Standard Preprocessor (yes, the one mentioned on the proposal) to be used on Exp 2.

In [ ]:
X = df.drop("price", axis=1)

# there would be a y in the real case

In [4]:
st = StandardPreprocessor()

X = st.transform(X)

In [5]:
X.head()

,temperature_2m,cloud_cover,wind_speed_10m,shortwave_radiation,total_load,generation_forecast,Price,Open,High,Low,...,hour_sin,hour_cos,day_of_week_sin,day_of_week_cos,month_sin,month_cos,quarter_sin,quarter_cos,weekend_sin,weekend_cos
0,0.275260,0.920,0.232164,0.0,0.459870,0.030112,NaN,NaN,NaN,NaN,...,-0.258819,0.965926,-0.781831,0.62349,0.5,0.866025,1.0,6.123234e-17,1.224647e-16,-1.0
1,0.271102,0.872,0.242576,0.0,0.419696,0.033842,NaN,NaN,NaN,NaN,...,0.000000,1.000000,0.000000,1.00000,0.5,0.866025,1.0,6.123234e-17,0.000000e+00,1.0
2,0.270686,0.706,0.253760,0.0,0.390513,0.038698,NaN,NaN,NaN,NaN,...,0.258819,0.965926,0.000000,1.00000,0.5,0.866025,1.0,6.123234e-17,0.000000e+00,1.0
3,0.271518,0.244,0.258774,0.0,0.377381,0.046702,NaN,NaN,NaN,NaN,...,0.500000,0.866025,0.000000,1.00000,0.5,0.866025,1.0,6.123234e-17,0.000000e+00,1.0
4,0.270686,0.406,0.258774,0.0,0.372970,0.054745,NaN,NaN,NaN,NaN,...,0.707107,0.707107,0.000000,1.00000,0.5,0.866025,1.0,6.123234e-17,0.000000e+00,1.0

In [6]:
X.describe()

,temperature_2m,cloud_cover,wind_speed_10m,shortwave_radiation,total_load,generation_forecast,Price,Open,High,Low,...,hour_sin,hour_cos,day_of_week_sin,day_of_week_cos,month_sin,month_cos,quarter_sin,quarter_cos,weekend_sin,weekend_cos
count,96133.000000,96133.000000,96133.000000,96133.000000,96133.000000,96133.000000,49488.000000,49488.000000,49488.000000,49488.000000,...,96133.000000,9.613300e+04,96133.000000,96133.000000,9.613300e+04,9.613300e+04,9.613300e+04,9.613300e+04,9.613300e+04,96133.000000
mean,0.478215,0.668799,0.240067,0.145746,0.556883,0.172929,0.114258,0.113726,0.114952,0.112734,...,-0.000060,-9.944924e-05,0.000590,0.000590,-6.602035e-03,-2.887859e-03,-6.844684e-03,3.255906e-03,3.493440e-17,0.429478
std,0.137524,0.319590,0.128979,0.221190,0.118048,0.162676,0.126408,0.126301,0.126960,0.125723,...,0.707131,7.070897e-01,0.707068,0.707152,7.057543e-01,7.084273e-01,7.059841e-01,7.081944e-01,5.529783e-17,0.903082
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,-1.000000,-1.000000e+00,-0.974928,-0.900969,-1.000000e+00,-1.000000e+00,-1.000000e+00,-1.000000e+00,0.000000e+00,-1.000000
25%,0.375884,0.430000,0.141149,0.000000,0.481716,0.052298,0.043136,0.042504,0.042464,0.042822,...,-0.707107,-7.071068e-01,-0.781831,-0.900969,-8.660254e-01,-8.660254e-01,-1.000000e+00,-1.836970e-16,0.000000e+00,-1.000000
50%,0.473181,0.758000,0.216352,0.006545,0.544884,0.121031,0.076709,0.076491,0.077435,0.075150,...,0.000000,-1.836970e-16,0.000000,-0.222521,-2.449294e-16,-1.836970e-16,-2.449294e-16,-1.836970e-16,0.000000e+00,1.000000
75%,0.578378,0.974000,0.313536,0.229519,0.635310,0.244744,0.117872,0.117513,0.119727,0.115641,...,0.707107,7.071068e-01,0.781831,0.623490,5.000000e-01,8.660254e-01,1.224647e-16,1.000000e+00,1.224647e-16,1.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000e+00,0.974928,1.000000,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.224647e-16,1.000000